#!/bin/bash
#
# Auteur: Redouane GUERMAT ( et les autres membres de la classe qui ont aider)
#
# Description: Ce script permet de passer  d'une nouvelle VM debian V0 à V1
#
# Mail: Redouane.g99@gmail.com
#
#
#
# set -e
# set -x
clear

  if [ ! $UID -eq 0 ]
  then
    echo "Veuillez lancer le script en mode ROOT"
    exit
  fi

function install_utils
{
        apt update && apt upgrade -y
        apt install vim sudo rsync git net-tools mlocate htop screen curl -y
}

function install_cheat
{
	# Téléchargement de cheat
	wget https://github.com/cheat/cheat/releases/download/4.2.3/cheat-linux-amd64.gz

	# Décompresser le programme
	gunzip cheat-linux-amd64.gz

	# Autoriser l'exécution à tout les utilisateurs
	chmod a+x cheat-linux-amd64

	# Déplacer le programme vers /usr/local/bin/
	mv -v cheat-linux-amd64 /usr/local/bin/cheat
}


function create_dirs
{
	# Créer les dossiers pour la conf
	mkdir -vp /opt/COMMUN/cheat/cheatsheets/community
	mkdir -v /opt/COMMUN/cheat/cheatsheets/personal
}

function configure_cheat
{
	# Générer la conf pour le script dans le bon fichier
	cheat --init > /opt/COMMUN/cheat/conf.yml

	# Changer le path de la conf générée
	sed -i 's;/root/.config/; /opt/COMMUN/;' /opt/COMMUN/cheat/conf.yml
}

function install_cheatsheets
{
	# télécharger les cheatsheets
	git clone https://github.com/cheat/cheatsheets.git

	# Les déplacer dans le dossier créé précédement
	mv -v cheatsheets/* /opt/COMMUN/cheat/cheatsheets/community
}

function config_dir_making
{
	# Créer les dossier .config chez root et /etc/skel
	mkdir -v /root/.config/
	mkdir -v /etc/skel/.config/
	make_root_bashrc
	make_skel_bashrc
}

function make_root_bashrc
{
	echo "umask 007" >> /root/.bashrc
	cat >> /root/.bashrc << EOF
export PS1="\[\033[38;5;1m\]\n[\t] \u@\h \w\n\\$ :\[$(tput sgr0)\] \[$(tput sgr0)\]"
alias ll='ls -rtl'
alias la='ls -lsa'
alias rm='rm -Iv --preserve-root'
alias chown="chown -v --preserve-root"
alias chmod="chmod -v --preserve-root"
alias chgrp="chgrp -v --preserve-root"
alias su="su - "
alias hs='history|grep -i '
EOF
}

function make_skel_bashrc
{
	echo "umask 007" >> /etc/skel/.bashrc
	cat >> /etc/skel/.bashrc << EOF
export PS1="\[\033[38;5;14m\]\n[\t]\u@\h \w\n\\$ :\[$(tput sgr0)\] \[$(tput sgr0)\]"
alias ll='ls -rtl'
alias la='ls -lsa'
alias rm='rm -Iv --preserve-root'
alias chown="chown -v --preserve-root"
alias chmod="chmod -v --preserve-root"
alias chgrp="chgrp -v --preserve-root"
alias su="su - "
alias hs='history|grep -i '
EOF
}

function make_user_bashrc
{
	echo "umask 007" >> /home/"$1"/.bashrc
	cat >> /home/$1/.bashrc << EOF
export PS1="\[\033[38;5;14m\]\n[\t]\u@\h \w\n\\$ :\[$(tput sgr0)\] \[$(tput sgr0)\]"
alias ll='ls -rtl'
alias la='ls -lsa'
alias rm='rm -Iv --preserve-root'
alias chown="chown -v --preserve-root"
alias chmod="chmod -v --preserve-root"
alias chgrp="chgrp -v --preserve-root"
alias su="su - "
alias hs='history|grep -i '
EOF
}

function group_create
{
	# Créer un groupe commun pour les droits sur les cheatsheets
	groupadd -g 10000 commun
	chgrp -Rv commun /opt/COMMUN
	chmod -Rv 2770 /opt/COMMUN/cheat/cheatsheets/personal
}

function create_esgi()
{
    #création du compte esgi avec pouir mdp Pa55w.rd comme demandé
    useradd -m -G 10000 -s /bin/bash esgi
    usermod -aG sudo esgi
    echo -e "Pa55w.rd\nPa55w.rd" |passwd esgi
}

function config_linking
{
	# Créer les liens symboliques pour les utilisateurs
	ln -vs /opt/COMMUN/cheat /root/.config/cheat
	ln -vs /opt/COMMUN/cheat /etc/skel/.config/cheat

	# Défini bash comme shell par défaut
	rm /bin/sh
	ln -vs /bin/bash /bin/sh

	# Récupérer une liste des utilisateur "legité
	users=($(grep '/bin/bash' /etc/passwd | awk -F : '{print $1}'))

	# Dans une boucle créer le dossier .config faire le lien symbolique et un ajouts aux groupes
	# Pour chaque utilisateurs sauf root
	for user in "${users[@]}"; do
		if [ $user != "root" ];
		then
			usermod -a -G commun $user
			usermod -a -G sudo $user
			mkdir /home/$user/.config
			ln -vs /opt/COMMUN/cheat /home/$user/.config/cheat
			chown -R "$user" /home/$user/.config
			make_user_bashrc $user
		fi
	done
}

echo "Début du script, passage de la V0 à la V1 imminent"
sleep 5
clear

echo "\n__________________________"
echo "Installation des utilitaires"
echo "__________________________\n"
install_utils
sleep 5

echo "\n__________________________"
echo "Installation de cheat"
echo "__________________________\n"
install_cheat
sleep 5

echo "\n__________________________"
echo "Creation des répertoires"
echo "__________________________\n"
create_dirs
sleep 5

echo "\n__________________________"
echo "Configuration de cheat"
echo "__________________________\n"
configure_cheat
sleep 5

echo "\n__________________________"
echo "Installion de cheatsheets"
echo "__________________________\n"
install_cheatsheets
sleep 5

echo "\n__________________________"
echo "Création dess répertoires .config"
echo "__________________________\n"
config_dir_making
sleep 5

echo "\n__________________________"
echo "Creation du groupe commun"
echo "__________________________\n"
group_create
sleep 5

echo "\n__________________________"
echo "Lier les configurations"
echo "__________________________\n"
config_linking
sleep 5

echo "\n__________________________"
echo "Création de l'utilisateur esgi"
echo "__________________________\n"
create_esgi
echo "L'utilisateur esgi à pour mdp Pa55w.rd"
sleep 5
